### ISSUE TITLE
syntax bikeshedding

### ISSUE THREAD

**Issue by PavelVozenilek** [MCSH/rumi#1]
Currently functions are defined like this:

```
stPrinter := (m: MyStruct) -> void
...
```
and structures like this:

```
MyStruct : struct 
...
```

This is not the easiest style for reading. The important information (this is function, this is structure) is not the very first thing one sees, it only appears only after potentially long name.

It would be IMO slightly more readable when the type of the definition comes first:

```
fn stPrinter(m: MyStruct) -> void
...

struct MyStruct 
...
```

It would also reduce a little bit visual noise made by `!@#$%^&*())__+|` characters.

This also applies to declaration of stack variables and structure members.

**Comment by MCSH** [comment]
Thank you for your suggestion. In our opinion the variable name is more important than three struct or function keyword. You are more than welcome to fork the project to change the grammar
